name: Generate Snake Animation

on:
  # Schedule: Update every 12 hours (adjust as needed)
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation with customization options (optional)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Haadesx  # Use your username
          outputs: dist/snake.svg
          # Add these lines for customization (uncomment and adjust values):
          # color_snake: orange  # Example snake color
          # color_dots: "#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"  # Example dot colors

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.1
        with:
          target_branch: main  # Adjust if using a different branch
          build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
