name: Generate Snake Animation

on:
  # Schedule: Update every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Haadesx  # Use your GitHub username
          outputs: dist/snake.svg
          # Uncomment and adjust for customization
          # color_snake: orange
          # color_dots: "#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Adjust if using a different branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
